NAME = iCalc
DESCRIPTION = "A better calculator for engineers"
COMPRESSED = NO
ARCHIVED = NO
CFLAGS = -Wall -Wextra -Oz
LTO = NO

EXTRA_C_SOURCES = \
  main.c \
  matrix.c \
  number.c \
  calculator.c \
  io.c \
  interface.c

include $(shell cedev-config --makefile)